### ISSUE TITLE
일정 만들기_일정 공유 및 채팅 - B

### ISSUE THREAD

**Issue by soyamilk0705** [TripTune-Project/TripTune-Backend#13]
### 📌 Description
일정 공유, 채팅 구현

### 📝 To-do
- [x] 공유한 참석자 조회 구현
- [x] 일정 공유 구현
- [x] 일정 참석자 권한 변경 구현
- [x] 채팅 구현
- [x] 채팅 예외 처리 구현
- [x] 테스트 코트
