### ISSUE TITLE
마이페이지_계정 탈퇴 - B

### ISSUE THREAD

**Issue by soyamilk0705** [TripTune-Project/TripTune-Backend#18]
### 📌 Description
마이페이지 중 계정 탈퇴 구현

### 📝 To-do
- [x] 계정 탈퇴 구현
- [x] 사용자 정보 익명 처리
- [x] 참석자 : 공유, 북마크 삭제
- [x] 작성자 : 일정, 공유, 여행 루트, 채팅, 북마크 삭제
- [x] 프로필 이미지 기본값으로 변경
- [x] 테스트 코트
