### ISSUE TITLE
여행지 탐색_첫 화면, 검색 - B

### ISSUE THREAD

**Issue by soyamilk0705** [TripTune-Project/TripTune-Backend#6]
### 📌 Description
여행지 탐색 진입 화면, 검색 기능 구현

### 📝 To-do
- [x] 여행지 탐색 진입 화면 구현
- [x] 여행지 탐색 검색 구현
- [x] 여행지 탐색 검색 시 위치 데이터 포함/미포함 검색으로 구현
- [x] 테스트 코트
