### ISSUE TITLE
일정 만들기_일정 생성 및 조회 - B

### ISSUE THREAD

**Issue by soyamilk0705** [TripTune-Project/TripTune-Backend#9]
### 📌 Description
일정 생성 및 목록 조회 구현

### 📝 To-do
- [x] 일정 생성 구현
- [x] 일정 생성 시 유효성 검증
- [x] 일정 목록 조회 구현
- [x] 전체 일정, 공유한 일정 조회로 분리
- [x] 테스트 코트
